export interface YTItem extends JsonResponse {
    kind: string;
    etag: string;
    id: string;
}

// Chassis for all subsequent received JSON network responses
export interface JsonResponse {
    [key: string]: unknown;
    error?: {
        code: number;
        message: string;
        errors: {
            message: string;
            domain: string;
            reason: string;
            location: string;
            locationType: string;
        }[]
    }
}

export interface YTResponse extends JsonResponse {
    kind: string;
    etag: string;
}

export interface YTListResponse extends YTResponse {
    nextPageToken?: string;
    prevPageToken?: string;
    pageInfo?: {
        totalResults: number;
        resultsPerPage: number;
    }
    items: YTItem[];
}



// Represents a video object (used both in cache and in manipulations)
export interface Video extends YTItem {
    statistics: {
        viewCount: number;
        likeCount: number;
        dislikeCount?: number;
        favoriteCount: number;
        commentCount: number;
    };
    snippet: {
        publishedAt: string;
        title: string;
        description: string;
        thumbnails: {
            default: {
                url: string;
                width: number;
                height: number;
            }
        };
        channelTitle: string;
        channelId: string;
    };
    contentDetails: {
        duration: string;
        regionRestriction?: {
            allowed?: string[];
            blocked?: string[];
        }
    };
    comments?: Comment[];
    commentsOpen?: string;
    commentNextPageToken?: string;
    autoGenerated?: boolean;
}

// Chassis for playlistItems API GET request response content
export interface PlaylistItemsResponse extends YTListResponse {
    items: PlaylistItem[];
}

// Is a raw approximation for a Video, and is only used in playlists, because playlist requests
// only provide the very essential info about their items, not enough to form a Video object
export interface PlaylistItem extends YTItem {
    contentDetails: {
        videoId: string;
    }
}

export interface Channel extends YTItem {
    snippet: {
        title: string;
        description: string;
        customUrl: string;
        publishedAt: string;
        thumbnails: {
            [key: string]: {
                url: string;
                width: number;
                height: number;
            }
        };
        defaultLanguage: string;
        localized: {
            title: string;
            description: string;
        }
        country: string;
    }
    contentDetails: {
        relatedPlaylists: {
            likes: string;
            favorites: string;
            uploads: string;
        }
    }
    statistics: {
        viewCount: number;
        subscriberCount: number;
        hiddenSubscriberCount: boolean;
        videoCount: number;
    }
    topicDetails: {
        topicIds: string[];
        topicCategories: string[];
    }
    status: {
        privacyStatus: string;
        isLinked: boolean;
        longUploadStatus: string;
        madeForKids: boolean;
        selfDeclaredMadeForKids: boolean;
    }
}

export interface ChannelsResponse extends YTListResponse {
    items: Channel[];
}

// Chassis for videos API GET request response content
export interface VideosResponse extends YTListResponse {
    items: Video[];
}

// Chassis for commentThreads API GET request by video ID response content
export interface CommentsResponse extends YTListResponse {
    items: Comment[];
}

// Chassis for comments API GET request by comment ID response content
export interface RepliesResponse extends YTResponse {
    items: Reply[];
}

// Represents a Comment object with all its descending properties and is used
// both in cache and in functions
export interface Comment extends YTItem {
    snippet: {
        channelId: string;
        videoId: string;
        topLevelComment: {
            kind: string;
            etag: string;
            id: string;
            snippet: {
                channelId: string;
                videoId: string;
                textOriginal: string;
                textDisplay: string;
                authorDisplayName: string;
                authorProfileImageUrl: string;
                authorChannelUrl: string;
                authorChannelId: {
                    value: string;
                };
                canRate: boolean;
                viewerRating: string;
                likeCount: number;
                publishedAt: string;
                updatedAt: string;
            }
        };
        canReply: boolean;
        totalReplyCount: number;
        isPublic: boolean;
    }
    replies?: {
        comments: Reply[];
    }
}

// Chassis for commentThreads API POST requests
export interface CommentEntity {
    snippet: {
        channelId: string;
        videoId: string;
        topLevelComment: {
            snippet: {
                textOriginal: string;
            }
        }
    }
}

// Reply object obtained via comments API GET request by a comment thread ID
export interface Reply extends YTItem {
    kind: string;
    etag: string;
    id: string;
    snippet: {
        channelId: string;
        videoId: string;
        textOriginal: string;
        textDisplay: string;
        parentId: string;
        authorDisplayName: string;
        authorProfileImageUrl: string;
        authorChannelUrl: string;
        authorChannelId: {
            value: string;
        };
        canRate: boolean;
        viewerRating: string;
        likeCount: number;
        publishedAt: string;
        updatedAt: string;
    }
}

// Chassis for comments API POST requests
export interface ReplyEntity {
    snippet: {
        textOriginal: string;
        parentId: string;
    }
}

// Interface for ipinfo API GET request responses (DEPRECATED starting from v1.0.8)
/* export interface IpinfoResponse extends JsonResponse {
    ip: string;
    hostname: string;
    city: string;
    region: string;
    country: string;
    loc: string;
    org: string;
    postal: string;
    timezone: string;
} */